# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tc < Formula
  desc ""
  homepage "https://tidalcontrol.com/"
  version "0.0.2"
  license "gpl-3.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/tidalcontrol/cli/releases/download/v0.0.2/tc_0.0.2_macos_arm64.tar.gz"
      sha256 "3de367edcae4627ec2ae48c2db86cbb201762fffa06caa7b264980cd9a75e315"

      def install
        bin.install "tc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tidalcontrol/cli/releases/download/v0.0.2/tc_0.0.2_macos_amd64.tar.gz"
      sha256 "5e638b4a4d8fab9ac75e7be0fbde749a4e55a5d611bbfd62f187ebfc824f62b0"

      def install
        bin.install "tc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tidalcontrol/cli/releases/download/v0.0.2/tc_0.0.2_linux_arm64.tar.gz"
      sha256 "43d796cdefadd833fa5427b9601bda1e102542cc61bac2111a746510ed78d834"

      def install
        bin.install "tc"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/tidalcontrol/cli/releases/download/v0.0.2/tc_0.0.2_linux_armv6.tar.gz"
      sha256 "4de6132cd9f738e182348b9890591953de3e93d3c75b2dfd91e3df0d04860cef"

      def install
        bin.install "tc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tidalcontrol/cli/releases/download/v0.0.2/tc_0.0.2_linux_amd64.tar.gz"
      sha256 "7487736c73c2a84a7ba8537d3e144633a66d4cabec0e7a025ed91605fab3424d"

      def install
        bin.install "tc"
      end
    end
  end
end
